from collections.abc import Callable
from typing import Any

class FileIndexCore:
    def __init__(self) -> None: ...
    def index_file(
        self, file_path: str, progress_callback: Callable[[int, int], Any] | None = None
    ) -> int: ...
    def get_offsets_range(self, start_idx: int, count: int) -> list[int]: ...
    def search_keyword(
        self,
        pattern: bytes,
        use_regex: bool = False,
    ) -> tuple[list[str], list[int], int]: ...
    def get_offset(self, index: int) -> int | None: ...
